name: Internal Incident Report
description: Report an incident reported by us
title: "[INCIDENT] "
type: "incident-internal-reported"
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Client Incident Report
        
        Please provide a clear and descriptive title above, replacing the placeholder.
        
  - type: dropdown
    id: incident-type
    attributes:
      label: Incident Type
      description: What type of incident is this?
      options:
        - Service Outage
        - Performance Issue
        - Security Issue
        - Data Issue
        - Bug/Error
        - Other
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a detailed description of the incident as reported by us
      placeholder: Describe what the client reported, including any relevant details about the issue
    validations:
      required: true
