name: Incident Report
description: Report an incident
title: "[INCIDENT] "
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Incident Report
        
        Please provide a clear and descriptive title above, replacing the placeholder.
        
  - type: dropdown
    id: reporter
    attributes:
      label: Reporter
      description: Who reported the incident
      options:
        - Internal
        - Client
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a detailed description of the incident as reported either by us or the client
      placeholder: Describe what the client reported, including any relevant details about the issue
    validations:
      required: true
